ALTER TABLE users
    ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS header_image_url TEXT;
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS location VARCHAR(100);
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS website VARCHAR(255);
